/* module.h */
goToNextFunc = 0x80001448;
goToFunc = 0x80001590;
module_createAndSetChild = 0x80001980;

/* model_info.h */
modelInfo_createRootNode = 0x80004e68;

/* actor_settings.h */
actor_model_set_pos = 0x801681C0;

/* player.h */
player_model = 0x80350990;
playerIsInsideActorSpawnRadius = 0x8015870C;
player_flags = 0x8035079C;

/* cv64.h */
ptr_array_8018CDE0 = 0x8018CDE0;
play_sound_in_position = 0x80013a48;